---
title: "SYS 5581 Project Concept Note"
author: "Nick Coronato"
date: "Due 2/15/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Predictive Capability for CPET Time Series Data**

\setlength\parindent{18pt}

  \indent Cardiopulmonary Exercise Testing (CPET) is used to evaluate performance of coordinated human biological subsystems during exercise to aid clinical decision-making. The test specifically measures responsiveness of the pulmonary, cardiovascular, neuropsychological, skeletal muscular, and hematopoietic systems. It has advantage of being low-risk, non-invasive, and simple to implement; the entire test lasts 40 minutes but includes only 10 minutes of exercise. Assessments during CPET are applicable to patients of all fitness ability levels. Exercise can be conducted on either treadmill or stationary cycle, each with their own advantages [1]. Typically, an initial rest phase is followed by a ramp protocol, in which work rate is gradually increased to the patient’s maximum ability. Research suggests that prescription of rehabilitation exercise programs is inadequate with analysis of CP signals from a resting patient; therefore, effective implementation of CPET in cardiac rehabilitation/intervention programs can optimize health outcomes [2].

\indent Important to CPET’s analytical utility is an understanding of Fick's Equation. This describes the maximum ability of an individual to take in and use oxygen; in other words, their functional aerobic capacity [3]. An individual’s max oxygen uptake ($VO_2 max$) is equal to the max stroke volume times max heart rate (cardiac output), multiplied by the difference between max arterial oxygen content and mixed venous oxygen content. 
 
<center>

$VO_2max = (SVmax * HRmax) * (CaO_2max - CvO_2max)$

</center>
 
 \setlength\parindent{18pt}
 
  \indent  Through continuous electrocardiogram and other measurements, the output data commonly recorded through CPET are: lung function through flow volume loops; blood pressure; oxygen consumption during exercise ($VO_2max$); ventilatory anaerobic threshold (VAT); heart performance; and blood gas measurement [4]. The data is described in a 9-panel report which can be leveraged for clinical diagnosis of cardiopulmonary (CP) abnormalities. Armed with the ability to analyze CPET reports, cardiologists should be able to definitively diagnose – or predict – these abnormalities.  
  
  \indent The integrated Translational Health Research Institute at the University of Virginia has acquired a CPET data set of 186 patients, along with some individualized health information. Each patient is identified with a "Type" of cardiovascular disease or malfunction. The time series data includes the CPET variables and the treadmill speed & elevation, recorded every 20 seconds for the duration of the exercise test.
  
  \indent I wish to discover hidden relationships in the features of the CPET test, which may be useful in predicting diagnosis or prognosis of heart failure/cardiovascular disease. Through exploratory data analysis, I hope to be able to model volatility in terms of "entropy" for the physiologic time series. In theory, as the body is put under stress, the physiological sub-systems should synchronize to meet the increased demand; individuals of high fitness can generally do this very well. When comparing healthy, diseased, and aging individuals, studies generally agree that the greatest amount of generalized entropy exists amongst healthy individuals. This is indicative of the theory that, as humans age and become less “healthy,” their systems lose robustness and cannot readily adapt [8], [9]. By analyzing “loss of complexity” as a feature, we could improve our diagnostic approaches for a wide class of diseases. 
\pagebreak

***BIBLIOGRAPHY***


[1]	“ATS/ACCP Statement on Cardiopulmonary Exercise Testing,” Am. J. Respir. Crit. Care Med., vol. 167, no. 2, pp. 211–277, Jan. 2003, doi: 10.1164/rccm.167.2.211.

[2]	M. Guazzi, F. Bandera, C. Ozemek, D. Systrom, and R. Arena, “Cardiopulmonary Exercise Testing: What Is its Value?,” J. Am. Coll. Cardiol., vol. 70, no. 13, pp. 1618–1636, Sep. 2017, doi: 10.1016/j.jacc.2017.08.012.

[3]	K. Albouaini, M. Egred, and A. Alahmar, “Cardiopulmonary exercise testing and its application,” Heart, vol. 93, no. 10, pp. 1285–1292, Oct. 2007, doi: 10.1136/hrt.2007.121558.

[4]	“Cardiopulmonary Exercise Testing (CPET).” http://www.geh.nhs.uk/directory-of-services/specialties-and-services/c/cardio-respiratory-unit-cru/cardiopulmonary-exercise-testing-cpet/ (accessed Jan. 25, 2021).

[5]	H. Hebestreit et al., “Cardiopulmonary Exercise Testing Provides Additional Prognostic Information in Cystic Fibrosis,” Am. J. Respir. Crit. Care Med., vol. 199, no. 8, pp. 987–995, Apr. 2019, doi: 10.1164/rccm.201806-1110OC.

[6]	N. J. Domnik, E. S. Walsted, and D. Langer, “Clinical Utility of Measuring Inspiratory Neural Drive During Cardiopulmonary Exercise Testing (CPET),” Front. Med., vol. 7, Sep. 2020, doi: 10.3389/fmed.2020.00483.

[7]	D. Popovic et al., “Quantification of coronary artery disease using different modalities of cardiopulmonary exercise testing,” Int. J. Cardiol., vol. 285, pp. 11–13, Jun. 2019, doi: 10.1016/j.ijcard.2019.03.012.

[8]	M. Costa and A. L. Goldberger, “Multiscale Entropy Analysis of Complex Physiologic Time Series,” Phys. Rev. Lett., vol. 89, no. 6, p. 4, 2002.

[9]	C.-K. Peng, M. Costa, and A. L. Goldberger, “ADAPTIVE DATA ANALYSIS OF COMPLEX FLUCTUATIONS IN PHYSIOLOGIC TIME SERIES,” Adv. Adapt. Data Anal., vol. 01, no. 01, pp. 61–70, Jan. 2009, doi: 10.1142/S1793536909000035.

